#Only RV mode is supported for now
hawkConnection:
   - displayName: "Domin 1"
     hawkDomain: "testDomain"
     rvService: "7474"
     rvNetwork: ";"
     rvDaemon: "tcp:7474"
     bwMicroagentNameMatcher: [".*bwengine.*"]

# number of concurrent tasks
numberOfThreads: 1

numberOfThreadsPerDomain: 5

taskSchedule:
    numberOfThreads: 1
    taskDelaySeconds: 60

#This will create this metric in all the tiers, under this path
metricPrefix: "Custom Metrics|Tibco BW|"

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Tibco BW"