#Only RV mode is supported for now
hawkConnection:
   - displayName: "Domin 1"
     hawkDomain: "testDomain"
     rvService: "7474"
     rvNetwork: ";"
     rvDaemon: "tcp:7474"
     bwMicroagentNameMatcher: [".*bwengine.*"]

# number of concurrent tasks
numberOfThreads: 1

taskSchedule:
    numberOfThreads: 1
    taskDelaySeconds: 60

#prefix used to show up metrics in AppDynamics
metricPrefix: "Custom Metrics|Tibco|"